module config
    !This module was automatically generated by building
    !geoalgs.  Modifications to this file will not be reflected
    !in the package's binary files and will be erased when
    !"make clean" is invoked.
    implicit none

    include "config.h"

    !f2py character(len=256) :: ancildat_path, install_path, bin_path, lib_path, inc_path, src_path

end module config
